// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"hurl1zobr0","name":"BlackbirdHome","description":"","endpoint":"https://hurl1zobr0.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/blackbird/contacts","/blackbird/contacts/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:21469931-6152-436c-923b-1a796e65db95',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'blackbirdhome-hosting-mobilehub-1568482055',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3akism9rzdtwx.cloudfront.net',
    'aws_mobile_analytics_app_id': '75fd5d92343347bcbcb74e94fda659c8',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '8acce425-7bab-4d79-9402-af8457420a0a',
    'aws_project_name': 'blackbird-home',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'blackbirdhome-deployments-mobilehub-1568482055',
    'aws_resource_name_prefix': 'blackbirdhome-mobilehub-1568482055',
}

export default awsmobile;
